### ISSUE TITLE
Parameter information not displaying correctly in VS Code...

### ISSUE THREAD

**Issue by pbrubaker** [matarillo/LanguageServerProtocol#8]
I am creating function signature help for a language that I'm enabling in VS Code.  I am having an issue where only one of the function parameters displays in VS Code.  Is this known behavior or am I doing something wrong?

```
SignatureHelp test = new SignatureHelp();

var sig = new SignatureInformation();
sig.label = "shuffle";
sig.documentation = "shuffle(float v, int i)";

sig.parameters = new []
{
	new ParameterInformation
	{
		label = "float",
		documentation = "Float register."
	},
	new ParameterInformation
	{
		label = "int",
		documentation = "Bits to shuffle."
	}
};

test.signatures = new SignatureInformation[1];
test.signatures[0] = sig;

return Result<SignatureHelp, ResponseError>.Success(test);
```

![lsp_signature](https://user-images.githubusercontent.com/6944373/45729604-12c76480-bb82-11e8-8af1-39a57aadb627.png)

Cheers,

Pete

**Comment by matarillo** [comment]
I will try to reproduce this later. Thanks for your feedback and patience.

**Comment by matarillo** [comment]
You should set `SignatureHelp.activeParameter` property calculated from the current cursor position specified with `TextDocumentPositionParams.position` property.

**Comment by pbrubaker** [comment]
Thank you!  I will give that a shot this evening.

**Comment by pbrubaker** [comment]
That fixed it, thank you!
